# Generated by Django 5.2.15 on 2026-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_uid', models.CharField(db_index=True, max_length=64)),
                ('ts', models.BigIntegerField()),
                ('uuid', models.CharField(blank=True, default='', max_length=64)),
                ('submission_id', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['form_uid', '-ts'], name='app_submiss_form_ui_627292_idx')],
            },
        ),
    ]
